;;; org-iv.el --- a tool used to view html generated by org-file immediately.

;; This is free and unencumbered software released into the public domain.

;; Author: kuangdash <kuangdash@163.com>
;; Version: 1.0.0
;; URL: https://github.com/kuangdash/org-iv.el
;; Package-Requires: ((impatient-mode 1.0.0) (org-mode 8.0))

;;; Commentary:

;; org-iv is a tool used to view html generated by org-file
;; immediately. Powered by impatient-mode.

;;; Code:

(require 'ox)
(require 'impatient-mode)

(defvar org-iv/root (file-name-directory load-file-name)
  "Where the current package loaded.")

(defvar org-iv/front-html-file (expand-file-name "org-iv-front-file.html" org-iv/root)
  "The file put on front of the html generated by org-file.")

(defvar org-iv/back-html-file (expand-file-name "org-iv-back-file.html" org-iv/root)
  "The file put on back of the html generated by org-file.")

(defvar org-iv/front-html-string nil
  "The string of org-iv/front-html-file.")

(defvar org-iv/back-html-string nil
  "The string of org-iv/back-html-file.")

;;;###autoload
(defun org-iv/immediate-view ()
  "Use impatient-mode to view html-file generated by org-file quickly."
  (interactive)
  (with-temp-buffer
    (insert-file-contents org-iv/front-html-file)
    (setq org-iv/front-html-string (buffer-string)))
  (with-temp-buffer
    (insert-file-contents org-iv/back-html-file)
    (setq org-iv/back-html-string (buffer-string)))
  (imp-visit-buffer)
  (imp-set-user-filter `(lambda (org-file)
                          "For use impatient-mode"
                          (let ((html-string (with-current-buffer org-file
                                               (org-export-as 'html nil nil t nil))))
                            (insert org-iv/front-html-string
                                    "\n"
                                    html-string
                                    "\n"
                                    org-iv/back-html-string))))
  (message "org-immediate-view: begin!!"))

(defun org-iv/stop-immediate-view ()
  "stop org-iv/immediate-view"
  (interactive)
  (when (imp-buffer-enabled-p (buffer-name))
    (impatient-mode)
    (when (yes-or-no-p "Stop the running http-server?: ")
      (httpd-stop))))

(provide 'org-iv)
