#+TITLE: View html generated by org-mode immediately
#+AUTHOR: 皐月中二
#+EMAIL: kuangdash@163.com

* Configure
Install it by =git-clone=  (Termporarily don't upload it to =melpa=)
#+BEGIN_SRC emacs-lisp
  (require 'org-iv)

  (org-iv/add-to-alist
     'org-iv/config-alist
     `(("config-001"
        :front-html-file ,(expand-file-name "default/org-iv-front-file.html" org-iv/root)
        ;; The file put on front of the html generated by org-file.
        :back-html-file ,(expand-file-name "default/org-iv-back-file.html" org-iv/root)
        ;; The file put on back of the html generated by org-file.
        :web-resource-dir ,(expand-file-name "default" org-iv/root)
        ;; where to store CSS and JS files
        :web-test-root "~/org-iv-test/"
        ;; where we copy the content of web-resource-dir into
        :web-test-port 9876)
        ("config-002"
         ;; ...
        )))
#+END_SRC

or, use 'use-package'
#+BEGIN_SRC emacs-lisp
  (use-package org-iv
    :defer t
    :commands org-iv/immediate-view
    :config
    (org-iv/add-to-alist
     'org-iv/config-alist
     `(("config-001"
        :front-html-file ,(expand-file-name "default/org-iv-front-file.html" org-iv/root)
        ;; The file put on front of the html generated by org-file.
        :back-html-file ,(expand-file-name "default/org-iv-back-file.html" org-iv/root)
        ;; The file put on back of the html generated by org-file.
        :web-resource-dir ,(expand-file-name "default" org-iv/root)
        ;; where to store CSS and JS files
        :web-test-root "~/org-iv-test/"
        ;; where we copy the content of web-resource-dir into
        :web-test-port 9876)
        ("config-002"
         ;; ...
        ))
     ))
#+END_SRC

* Usage
Use commands =org-iv/immediate-view= and =org-iv/stop-immediate-view= , you can bind the key you like in emacs.

Or, when the org-file is being larger and larger, the response of org-iv will be slower and slower. In order to change the situation, you can use =org-iv/manually-update= command，and from that time，you must use the command to see the change.

And, there is another method: =Narrow-to-region=. When org-iv is too slow, consider use it and use =org-iv/immediate-view= to see the region changes.

* Machanism
Open the "default" directory, you can see two files:
+ org-iv-front-file.html
+ org-iv-back-file.html

These two files are put before and after the html generated by org-mode respectively.
#+BEGIN_SRC html
  <html>
  <head>...</head>
  <body><!--org-iv-front-file.html-->

  <!--Html generated by org-mode-->

  </body><!--org-iv-back-file.html-->
  </html>
#+END_SRC
